headscale_domain: "{{ lookup('env', 'HEADSCALE_DOMAIN') | default('headscale.' + lookup('env', 'STAGING_SERVER_HOST') | replace('.', '-') + '.sslip.io') }}"
tailnet_suffix: "{{ lookup('env', 'TAILNET_SUFFIX') | default('tailnet.' + lookup('env', 'STAGING_SERVER_HOST') | replace('.', '-') + '.sslip.io') }}"
headscale_image: headscale/headscale@sha256:51b1b9182bb6219e97374fa89af6b9320d6f87ecc739e328d5357ea4fa7a5ce3
caddy_image: caddy@sha256:1e40b251ca9639ead7b5cd2cedcc8765adfbabb99450fe23f130eefabf50f4bc
