all:
  children:
    control_plane:
      hosts:
        ubuntu-0:
          ansible_host: "{{ lookup('env', 'STAGING_SERVER_HOST') }}"
          ansible_user: ubuntu
          ansible_become: true
          ansible_become_password: "{{ lookup('env', 'STAGING_SERVER_PASS') }}"
          ansible_ssh_pass: "{{ lookup('env', 'STAGING_SERVER_PASS') }}"
