all:
  children:
    control_plane:
      hosts:
        ubuntu-0:
          ansible_host: "{{ lookup('env', 'HEADSCALE_SERVER_HOST') }}"
          ansible_user: root
    operator_hosts:
      hosts:
        ubuntu-master:
          ansible_host: "{{ lookup('env', 'UBUNTU_MASTER_HOST') }}"
          ansible_user: h
    ubuntu_nodes:
      hosts:
        ubuntu-1:
          ansible_host: "{{ lookup('env', 'UBUNTU_1_HOST') }}"
          ansible_user: david
    mac_nodes:
      hosts:
        mac-1:
          ansible_host: "{{ lookup('env', 'MAC_1_HOST') }}"
          ansible_user: user
    windows_nodes:
      hosts:
        win-1:
          ansible_host: "{{ lookup('env', 'WIN_1_HOST') }}"
